version: 2.1

jobs:
  build-and-deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
