version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
