version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "12.16.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installation
                command: yarn install
            - run:
                name: Configuration
                command: |
                  git config user.email "rholang"
                  git config user.name "rholang"
            - add_ssh_keys:
                fingerprints:
                  - "3f:8e:9c:4b:61:19:40:be:cc:9a:4e:1d:d8:b2:be:8a"
            - run:
                name: Deploy to GH
                command: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: source
