version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "12.16.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installation
                command: yarn install
            - run:
                name: Configuration
                command: |
                  git config user.email "rholang"
                  git config user.name "rholang"
            - add_ssh_keys:
                fingerprints:
                  - "01:a0:26:02:e0:b9:43:ba:11:61:3f:76:e7:03:0a:07"
            - run:
                name: Deploy to GH
                command: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: source
