version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
