version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-deploy:
    install:
      steps:
        - checkout
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
              - yarn-packages-{{ checksum "yarn.lock" }}
        - run:
            name: Install Dependencies
            command: yarn --network-timeout 600000
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
              - ~/.cache/yarn

    deploy:
      steps:
        - run:
            name: Deploy  to GH-Pages
            command: yarn deploy

    lint:
      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: Run ESLint
            command: yarn run lint

    test-unit:
      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: Run unit tests
            command: yarn run test:unit

workflows:
  build-deploy:
    jobs:
      - install
      - deploy
