version: 2.1
orbs:
  node: circleci/node:latest-browsers
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "12.16.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
