version: 2.1

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: vuejs/ci

jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "12.16.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
