version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: vuejs/ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --network-timeout 600000
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  deploy:
    steps:
      - run:
          name: Deploy to GH-Pages
          command: yarn deploy

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run ESLint
          command: yarn run lint

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit tests
          command: yarn run test:unit

workflows:
  version: 2
  lint-and-test:
    jobs:
      - install
      - deploy
