version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.16.1

    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
