version: 2.1

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: vuejs/ci

jobs:
  build-and-deploy:
    steps:
      - checkout
      - run: yarn install
      - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
