version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "12.16.1"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installation
                command: yarn install
            - run:
                name: Configuration
                command: |
                  git config user.email "rholang"
                  git config user.name "rholang"
            - add_ssh_keys:
                fingerprints:
                  - "79:e4:66:d2:6f:28:b5:e5:d6:7e:de:f6:d1:fc:28:9d"
            - run:
                name: Deploy to GH
                command: yarn deploy
workflows:
  build-and-test:
    jobs:
      - build-and-deploy
